# Generated by Django 3.1.7 on 2021-04-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemailinglist',
            name='case',
            field=models.ForeignKey(default='Europe/Minsk', on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='Дело'),
            preserve_default=False,
        ),
    ]
